### ISSUE TITLE
Need a way to generate more than a few images

### ISSUE THREAD

**Issue by VisionaryMind** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#156]
Please share any tricks you have to get beyond what appears to be the 5 image limit. After ~5 generations, the interface breaks and begins generating 10+ random temporary layers and white images with no content. At that point, I have found the only way to reset the interface is to completely reboot the machine. Recycling Photoshop or Automatic1111 does nothing. 

Also, is there an ETA on Controlnet functionality? I see it in its own tab, but it does not yet have any effect on the image. On the contrary, enabling Controlnet causes the generation to run to about 5%, then stop without generating anything.

**Comment by AbdullahAlfaraj** [comment]
I can generate at least 20 images. 

![7CkZ6cKEZw](https://user-images.githubusercontent.com/7842232/224479451-d1bd0497-634e-479b-9f4c-5000d7365eff.gif)
You are limited by the amount of VRAM you have. If you go above, you will crash Automatic1111, and you will need to restart it. No need to restart photoshop or the plugin in this case.
What is your use case scenario for wanting to generate large batches at once? 


For ControlNet make sure it's up to date and that it has been set up correctly.#153

**Comment by VisionaryMind** [comment]
@AbdullahAlfaraj Thanks for the quick reply.

I am not trying to generate images in batch. Just a single image at 25 steps. It will work a few times but then suddenly start creating a completely white image. Right now, even after a reboot, inpainting doesn't work at all. Outpainting is fine. It's the inpainting that creates a **completely white image** and then tries to inpaint it (without any reference to the original image). I am surprised no one else has seen this behavior. I do wish it would work all the time, but as I said in the title, it's hit or miss.

**Comment by VisionaryMind** [comment]
I have figured out the problem. Between sessions (i.e. images), the layer deletion button must be clicked. Closing the image and opening a new one does not clear this cache. It works every time now, as long as that button is clicked:

![image](https://user-images.githubusercontent.com/47434136/224497038-c4eeb9bf-f083-451b-b741-6809180b1b7b.png)

**Comment by VisionaryMind** [comment]
Controlnet (latest version) is still failing with this error message:

```
Traceback (most recent call last):
  File "D:\Downloads\stable-diffusion-webui-v2\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui-v2\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 158, in process_batch
    if not args[0]:
IndexError: tuple index out of range
```
Settings used:

- Img2img
- Depth pre-processing and model
- Original

**Comment by VisionaryMind** [comment]
Latest version (v1.2.2) does not fix this problem. ControlNet is still not influencing the image in any way. Img2Img generates an unrelated mask on the ControlNet tab but does not update the image itself. It doesn't matter what settings are selected in the ControlNet tab. OpenPose, for example, is completely ignored. The resulting image is absolutely nothing like the original.

On the backend (via API), it is clear that the plugin is not using ControlNet at all (even though it is enabled in the GUI).

**Comment by AbdullahAlfaraj** [comment]
@VisionaryMind all components will need to be updated:
you will need to update your Auto1111 and ControlNet extension too.

> Also -- all SmartPresets have disappeared for all tabs. All options are missing.

In your attached image, it shows that you are using the "Maintain Composition" preset. so, did it get resolved?

**Comment by VisionaryMind** [comment]
@AbdullahAlfaraj I can confirm that all of my components are the latest versions. Automatic1111 has been updated to the latest  with a UI restart and here are the extensions:

![image](https://user-images.githubusercontent.com/47434136/225134669-cfd0a922-d4ea-48a9-9910-59354e011f91.png)

While the SmartPresets issue was resolved with a restart, ControlNet is still not working.

**Comment by VisionaryMind** [comment]
I followed the advice in [#172](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/172). It is working splendidly now. Thank you! I'll keep a look-out for your update.
