### ISSUE TITLE
fail to read an image file

### ISSUE THREAD

**Issue by 4DeepThought2** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#185]
I see multiple past attempts to fix this, but hitting it on recent build. 

```
payload: {'init_image_name': 'Background_1_408597.png'}
exception:fail to read an image file ./init_images/Background_1_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Background_1_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Background_1_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56073 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
getInitImageHandle:

payload: {'init_image_name': 'Color Fill 1_20_408597.png'}
exception:fail to read an image file ./init_images/Color Fill 1_20_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Color Fill 1_20_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Color Fill 1_20_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56074 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
getInitImageHandle:

payload: {'init_image_name': 'Layer 0_21_408597.png'}
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56120 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
getInitImageHandle:

payload: {'init_image_name': 'Layer 0_21_408597.png'}
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Layer 0_21_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56120 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
getInitImageHandle:

payload: {'init_image_name': 'Group 1_mask_23_408597.png'}
exception:fail to read an image file ./init_images/Group 1_mask_23_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Group 1_mask_23_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Group 1_mask_23_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56120 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
getInitImageHandle:

payload: {'init_image_name': 'Layer 0 copy_22_408597.png'}
exception:fail to read an image file ./init_images/Layer 0 copy_22_408597.png, will try again 0 of 3
exception:fail to read an image file ./init_images/Layer 0 copy_22_408597.png, will try again 1 of 3
exception:fail to read an image file ./init_images/Layer 0 copy_22_408597.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:56120 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m
```

**Comment by 4DeepThought2** [comment]
Additional Issues.  Is there a dummies guide for img2img or inpaint?  I can generally figure these things out, but this tool has never seemed to work for me with inpaint/img2img.  Im sure Im doing something wrong.

`←[32mINFO←[0m:     127.0.0.1:52808 - "←[1mPOST /img2img/ HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server\python_server\.\serverMain.py", line 176, in img2ImgHandle
    dir_name,images_info,metadata = await img2imgapi.img2ImgRequest(sd_url,payload)
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server\python_server\.\img2imgapi.py", line 95, in img2ImgRequest
    init_img = Image.open(f"{init_img_dir}/{init_img_name}")
  File "Z:\Programs\stable-diffusion-ui\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\PIL\Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './init_images/Color Fill 1_4_737254.png'
←[32mINFO←[0m:     127.0.0.1:52811 - "←[1mGET /sdapi/v1/progress?skip_current_image=false HTTP/1.1←[0m" ←[32m200 OK←[0m`

**Comment by AbdullahAlfaraj** [comment]
Which method did you use to install the plugin? 
Instead of using the old start_server.bat file, I would recommend that you install our Auto1111 extension. This way it will run automatically when you start the Automatic1111 WebUI, and the installation process and instructions can be found on the readme page.

**Comment by 4DeepThought2** [comment]
Oh interesting.  I installed it with the one click (option 1)  I have your extension installed as well, but it doesnt seem to run when I start Automatic1111.  Ill take another look.

**Comment by 4DeepThought2** [comment]
lol.  I was running both.  Thanks.
