### ISSUE TITLE
Coordinate 'right' is less than 'left'

### ISSUE THREAD

**Issue by 4DeepThought2** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#192]
I think this has something to do with controlnet, but not sure.  I dont have much more on it yet.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "Z:\Programs\stable-diffusion-ui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "Z:\Programs\stable-diffusion-ui\extensions\sd-webui-controlnet\scripts\api.py", line 117, in controlnet_img2img
    return self.controlnet_any2img(
  File "Z:\Programs\stable-diffusion-ui\extensions\sd-webui-controlnet\scripts\api.py", line 133, in controlnet_any2img
    return original_callback(self_copy, any2img_request)
  File "Z:\Programs\stable-diffusion-ui\modules\api\api.py", line 310, in img2imgapi
    processed = process_images(p)
  File "Z:\Programs\stable-diffusion-ui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "Z:\Programs\stable-diffusion-ui\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "Z:\Programs\stable-diffusion-ui\modules\processing.py", line 959, in init
    mask = mask.crop(crop_region)
  File "Z:\Programs\stable-diffusion-ui\venv\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'
```

**Comment by 4DeepThought2** [comment]
Ah.  This happens when the Width/Height isnt set to the correct image size, during inpaint.

**Comment by AbdullahAlfaraj** [comment]
> Ah. This happens when the Width/Height isnt set to the correct image size, during inpaint.

can you give an example?

**Comment by Eyeror** [comment]
> > Ah. This happens when the Width/Height isnt set to the correct image size, during inpaint.
> 
> can you give an example?

I don't know if this help. I just run SD on edge(almost no extension) instead of chrome(try to turn off all extensions but not working) and problem solved.
