### ISSUE TITLE
after Automatic 1111 webui update , 'value error: images do not match' while inpainting using the colab

### ISSUE THREAD

**Issue by peacetemple** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#198]
wondering if I should wait for the Automatic 1111 webui's next update, or if automatic1111.ipynb will be updated as well

(on my desktop version of automatic 1111 webui, I reverted to an old version of the webui with git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24 as suggested  https://www.reddit.com/r/StableDiffusion/comments/121kqkd/psa_hold_up_with_updating_automatic1111_for_now/ 
and the inpainting worked, unfortunately my graphics card is not powerful enough and really enjoyed using your colab)

Thank you for any help

Startup time: 69.2s (import torch: 1.3s, import gradio: 1.2s, import ldm: 0.4s, other imports: 5.3s, list SD models: 27.9s, setup codeformer: 0.2s, load scripts: 0.9s, load SD checkpoint: 28.8s, create ui: 0.6s, gradio launch: 2.4s, scripts app_started_callback: 0.2s).
  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:08<02:40,  8.43s/it]
 10% 2/20 [00:08<01:05,  3.61s/it]
 15% 3/20 [00:08<00:35,  2.07s/it]
 20% 4/20 [00:09<00:21,  1.35s/it]
 25% 5/20 [00:09<00:14,  1.05it/s]
 30% 6/20 [00:09<00:09,  1.40it/s]
 35% 7/20 [00:09<00:07,  1.79it/s]
 40% 8/20 [00:10<00:05,  2.18it/s]
 45% 9/20 [00:10<00:04,  2.55it/s]
 50% 10/20 [00:10<00:03,  2.88it/s]
 55% 11/20 [00:10<00:02,  3.17it/s]
 60% 12/20 [00:11<00:02,  3.41it/s]
 65% 13/20 [00:11<00:01,  3.59it/s]
 70% 14/20 [00:11<00:01,  3.72it/s]
 75% 15/20 [00:11<00:01,  3.83it/s]
 80% 16/20 [00:12<00:01,  3.88it/s]
 85% 17/20 [00:12<00:00,  3.78it/s]
 90% 18/20 [00:12<00:00,  3.66it/s]
 95% 19/20 [00:12<00:00,  3.71it/s]
100% 20/20 [00:13<00:00,  1.52it/s]
  0% 0/15 [00:00<?, ?it/s]
  7% 1/15 [00:03<00:47,  3.41s/it]
 13% 2/15 [00:03<00:20,  1.60s/it]
 20% 3/15 [00:04<00:12,  1.03s/it]
 27% 4/15 [00:04<00:08,  1.32it/s]
 33% 5/15 [00:04<00:06,  1.65it/s]
 40% 6/15 [00:05<00:04,  1.94it/s]
 47% 7/15 [00:05<00:03,  2.19it/s]
 53% 8/15 [00:05<00:02,  2.38it/s]
 60% 9/15 [00:06<00:02,  2.53it/s]
 67% 10/15 [00:06<00:01,  2.64it/s]
 73% 11/15 [00:06<00:01,  2.72it/s]
 80% 12/15 [00:07<00:01,  2.77it/s]
 87% 13/15 [00:07<00:00,  2.82it/s]
 93% 14/15 [00:07<00:00,  2.73it/s]
100% 15/15 [00:08<00:00,  1.81it/s]
API error: POST: https://75e5af2ce0bcd36f65.gradio.live/sdapi/v1/img2img {'error': 'ValueError', 'detail': '', 'body': '', 'errors': 'images do not match'}
Traceback (most recent call last):
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/api/api.py", line 144, in exception_handling
    return await call_next(request)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/content/stable-diffusion-webui/modules/api/api.py", line 109, in log_and_time
    res: Response = await call_next(req)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/api/api.py", line 355, in img2imgapi
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 694, in process_images_inner
    image_mask_composite = Image.composite(image.convert('RGBA').convert('RGBa'), Image.new('RGBa', image.size), p.mask_for_overlay.convert('L')).convert('RGBA')
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/PIL/Image.py", line 3341, in composite
    image.paste(image1, None, mask)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/PIL/Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

**Comment by AbdullahAlfaraj** [comment]
Yes, I can confirm this. the latest Automatic1111 update has an issue where inpaint and outpaint mode won't work properly unless the image resolution is divisible by 8, see [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9092#issuecomment-1487520033)  
for example 512x579 will work fine in txt2img and img2img mode but it will throw ```ValueError: images do not match``` error in  inpaint and outpaint
