### ISSUE TITLE
ControlNet not working properly.  

### ISSUE THREAD

**Issue by kaokaojap** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#210]
I'm using win10 and photoshop 2023.  Whenever I attempt to create any image using controlnet, nothing will be generated and I will receive these error messages:

[ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 107, in controlnet_img2img
    return self.controlnet_any2img(
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 116, in controlnet_any2img
    alwayson_scripts = dict(any2img_request.alwayson_scripts)
AttributeError: 'ControlNetStableDiffusionProcessingImg2Img' object has no attribute 'alwayson_scripts'

**Comment by AbdullahAlfaraj** [comment]
As the error message says the controlnet endpoints have been deprecated and we need to update the api to use the new schema
I will merge the solution #201 soon after testing it with the latest controlnet  and Auto1111 versions.

**Comment by AbdullahAlfaraj** [comment]
@kaokaojap can you screenshot your installed extension page. I need to see what version of controlnet you're using.
![image](https://user-images.githubusercontent.com/7842232/230557945-caeee1ab-e666-460b-a0e7-720cd694a071.png)
I'm assuming you are using an older version of automatic1111 or controlnet because I've tested the plugin v1.2.2 with the latest version of auto1111 and the latest version of controlnet released on Mar 23 and it seems to work fine even without adapting to the new the api schema.

**Comment by drawtide** [comment]
@AbdullahAlfaraj  @kaokaojap  I have the same problem and a similar log error message. **Later I updated automatic 1111 and it solved the problem.**

**Comment by sh570655308** [comment]
I find that if all setting about control net are deleted from "config.json", the plugin works fine, however this means the multi control net function is disabled. Then I try to add "control_net_max_models_num": 3 in "config.json", the problem occurs again.
All the operations above are under the latest version of auto1111,control net and this photoshop plugin.

**Comment by sh570655308** [comment]
I downgraded the a1111 version to a9fed7c, which is the last version before gradio 3.22 support, and then the multi control net problem solved.
