### ISSUE TITLE
ControlNet 1.1 error 

### ISSUE THREAD

**Issue by a70m123r** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#230]
ControlNet 1.1 is throwing this error, tried with few models.

> [ControlNet] warning: using deprecated '/controlnet/txt2img' route
[ControlNet] warning: consider using the '/sdapi/v1/txt2img' route with the 'alwayson_scripts' json property instead
Error running process: C:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 736, in process
    resize_mode = external_code.resize_mode_from_value(unit.resize_mode)
  File "C:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 28, in resize_mode_from_value
    return ResizeMode(value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'Scale to Fit (Inner Fit)' is not a valid ResizeMode <

**Comment by wuyue0509** [comment]
same error,how to fix it?

**Comment by a70m123r** [comment]
> same error,how to fix it?

The API interface needs updating to the new version. hope it happens soon, amazing plugin!

**Comment by a70m123r** [comment]
> > same error,how to fix it?
> 
> The API interface needs updating to the new version. hope it happens soon, amazing plugin!

Disregard that 

![image](https://user-images.githubusercontent.com/106325568/233214979-116190de-73f3-4093-bbd9-ba285d017b94.png)
Uncheck this in the AUTO 1111 settings, everything working now

**Comment by wuyue0509** [comment]
thx a lot

**Comment by Rey-94** [comment]
it just got fixed for me with the new controlnet update from mikubill

**Comment by wuyue0509** [comment]
Yes, I have also solved it, thanks anyway


五月丨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 晚上6:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin] ControlNet 1.1 error  (Issue #230)





 
it just got fixed for me with the new controlnet update from mikubill

**Comment by wuyue0509** [comment]
Yes, I have also solved it, thanks anyway

**Comment by Tatsu613** [comment]
please help.
It says to install control net as a photoshop plugin.
control net is installed with Automatic1111.

Will updating the control net fix it?
Currently at v1.1.448.
In the extensions tab, check for updates says "new commits".
How should I update control net?

I don't know much about this, so it would be helpful if you could explain it to me.
![2024-05-07_18h33_31](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/136796130/52959a4f-8183-40fe-9404-b6539420e24a)
