### ISSUE TITLE
ControlNet error

### ISSUE THREAD

**Issue by Lute-4** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#236]
> [ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
Error running process: C:\Users\Utilisateur\Downloads\AUTOMATIC1111_test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Downloads\AUTOMATIC1111_test\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\Users\Utilisateur\Downloads\AUTOMATIC1111_test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 791, in process
    unit = self.parse_remote_call(p, unit, idx)
  File "C:\Users\Utilisateur\Downloads\AUTOMATIC1111_test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 634, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'str' object has no attribute 'enabled'

Any idea?

**Comment by woofodus** [comment]
I'm having the exact same issue, thought it was because I was using older ControlNet, but I just updated everything and all the models and it's giving same error.

**Comment by zombieyang** [comment]
See #242 and maybe it is a solution.

**Comment by woofodus** [comment]
Disabling multi-ControlNet fixes the issue. I tried whatever this was https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/242 but it didn't do anything.
