### ISSUE TITLE
Img2img stuck at 1% if ControlNet is enabled

### ISSUE THREAD

**Issue by John-Keyberg** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#243]
Img2img stuck at 1% if ControlNet is enabled. It works normally with txt2img.

Maybe this is a bug, or maybe I'm doing something wrong. It would be great if the documentation could be updated for ControlNet - there currently isn't anything about it there.

**Comment by zombieyang** [comment]
Are there any error message in SD's console?

**Comment by John-Keyberg** [comment]
To create a public link, set `share=True` in `launch()`.
Startup time: 136.4s (import torch: 12.7s, import gradio: 6.6s, import ldm: 2.8s, other imports: 7.4s, list SD models: 0.5s, setup codeformer: 0.6s, load scripts: 1.8s, load SD checkpoint: 102.9s, create ui: 0.6s, gradio launch: 0.3s, scripts app_started_callback: 0.2s).
['control_canny-fp16 [e3fe7712]', 'control_depth-fp16 [400750f6]', 'control_hed-fp16 [13fee50b]', 'control_mlsd-fp16 [e3705cfa]', 'control_normal-fp16 [63f96f7c]', 'control_openpose-fp16 [9ca67cc5]', 'control_scribble-fp16 [c508311e]', 'control_seg-fp16 [b9c1cc12]', 't2iadapter_canny-fp16 [f2e7f7cd]', 't2iadapter_color-fp16 [743b5c62]', 't2iadapter_depth-fp16 [2c829a81]', 't2iadapter_keypose-fp16 [e3943bb9]', 't2iadapter_openpose-fp16 [4286314e]', 't2iadapter_seg-fp16 [0e677718]', 't2iadapter_sketch-fp16 [75b15924]', 't2iadapter_style-fp16 [0e2e8330]']
['control_canny-fp16 [e3fe7712]', 'control_depth-fp16 [400750f6]', 'control_hed-fp16 [13fee50b]', 'control_mlsd-fp16 [e3705cfa]', 'control_normal-fp16 [63f96f7c]', 'control_openpose-fp16 [9ca67cc5]', 'control_scribble-fp16 [c508311e]', 'control_seg-fp16 [b9c1cc12]', 't2iadapter_canny-fp16 [f2e7f7cd]', 't2iadapter_color-fp16 [743b5c62]', 't2iadapter_depth-fp16 [2c829a81]', 't2iadapter_keypose-fp16 [e3943bb9]', 't2iadapter_openpose-fp16 [4286314e]', 't2iadapter_seg-fp16 [0e677718]', 't2iadapter_sketch-fp16 [75b15924]', 't2iadapter_style-fp16 [0e2e8330]']
[ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
API error: POST: http://127.0.0.1:7860/controlnet/img2img {'error': 'AttributeError', 'detail': '', 'body': '', 'errors': "'str' object has no attribute 'enabled'"}
Traceback (most recent call last):
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI Generation\stable-diffusion-webui\modules\api\api.py", line 145, in exception_handling
    return await call_next(request)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "E:\AI Generation\stable-diffusion-webui\modules\api\api.py", line 110, in log_and_time
    res: Response = await call_next(req)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI Generation\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI Generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 107, in controlnet_img2img
    return self.controlnet_any2img(
  File "E:\AI Generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 120, in controlnet_any2img
    result = original_callback(self, any2img_request)
  File "E:\AI Generation\stable-diffusion-webui\modules\api\api.py", line 374, in img2imgapi
    processed = process_images(p)
  File "E:\AI Generation\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "E:\AI Generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
    cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
  File "E:\AI Generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 185, in get_cn_batches
    units = [copy(unit) for unit in units if unit.enabled]
  File "E:\AI Generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 185, in <listcomp>
    units = [copy(unit) for unit in units if unit.enabled]
AttributeError: 'str' object has no attribute 'enabled'

**Comment by zombieyang** [comment]
see if #242 could help

**Comment by wuyue0509** [comment]
txt2img and Img2img stuck at 0%  if ControlNet is enabled,how to fix it?

**Comment by fractalfantasy** [comment]
having this  issue too, although nothing in the console. just stuck at 0%

deactivating multiple control nets doesnt help

**Comment by AbdullahAlfaraj** [comment]
This issue is caused by an outdated ControlNet endpoint. To resolve it, update your plugin to v1.2.3 to use the new API.
