### ISSUE TITLE
Having issue with t2i adapter - color. Others work fine

### ISSUE THREAD

**Issue by drprs** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#249]
I am not able to use the color preprocessor in control net. I get the following error

[ControlNet] warning: using deprecated '/controlnet/img2img' route
[ControlNet] warning: consider using the '/sdapi/v1/img2img' route with the 'alwayson_scripts' json property instead
Error running process: K:\A111 Web UI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "K:\A111 Web UI\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "K:\A111 Web UI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 685, in process
    resize_mode = external_code.resize_mode_from_value(unit.resize_mode)
  File "K:\A111 Web UI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 28, in resize_mode_from_value
    return ResizeMode(value)
  File "C:\Users\drpra\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\drpra\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'Scale to Fit (Inner Fit)' is not a valid ResizeMode

**Comment by AbdullahAlfaraj** [comment]
This issue has been resolved in [v1.2.3](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/releases/tag/v1.2.3)
