### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by loretoparisi** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#29]
Will Photoshop for macOS be supported?

**Comment by AbdullahAlfaraj** [comment]
I haven't tested it on MacOS, but I don't see why it shouldn't work.
it should be OS agnostic.

**Comment by jackhagley** [comment]
I thought I would put this in the macOS thread rather than start a new one.

All seems to be installed correctly. Followed all the steps. But the progress bar is stuck at 0%!

I’m using Ventura 13.0.1. Photoshop is 24.1.0
During installation I had to change all the `python` commands in `./start_server.sh` to `python3`. But I think this is more of a PATH issue than anything else (I’m absolutely not very technical about this kind of thing).

Happy to help test and debug on mac if needed. Thanks so much for this plugin. It looks like it will really change things for a lot of people.

**Comment by jackhagley** [comment]
I’m getting an error, but it is a different error:

```
INFO:     Application startup complete.
INFO:     127.0.0.1:54185 - "GET /sdapi/v1/sd-models HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54186 - "GET /sdapi/v1/samplers HTTP/1.1" 404 Not Found
couldn't read the manifest.json
INFO:     127.0.0.1:54187 - "GET /version HTTP/1.1" 200 OK
txt2ImgHandle: 

payload:  {'prompt': 'cute cat', 'negative_prompt': '', 'steps': '20', 'sampler_index': 'Euler a', 'width': 512, 'height': 512, 'batch_size': '1', 'cfg_scale': 7, 'seed': '-1', 'mask_blur': 0, 'use_prompt_shortcut': True}
prompt_shortcut.json is not found
raw_keywords:  []
strip_keywords:  []
original_substrings:  []
final text:  cute cat
raw_keywords:  []
strip_keywords:  []
original_substrings:  []
final text:  
fullpath: /Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server/python_server/output/2022-12-30
INFO:     127.0.0.1:54199 - "POST /txt2img/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server_env/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server/python_server/./serverMain.py", line 154, in txt2ImgHandle
    dir_name,image_paths,metadata = await txt2ImgRequest(payload)
  File "/Users/jh/Auto-Photoshop-StableDiffusion-Plugin/server/python_server/./serverMain.py", line 46, in txt2ImgRequest
    for i in r['images']:
KeyError: 'images'
INFO:     127.0.0.1:54203 - "GET /sdapi/v1/progress?skip_current_image=false HTTP/1.1" 404 Not Found
```

**Comment by ambiSk** [comment]
I am also getting this, and my checkpoints are not loading
I am using a remote server so I have exported the environment variable
```
INFO:     127.0.0.1:54185 - "GET /sdapi/v1/sd-models HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54186 - "GET /sdapi/v1/samplers HTTP/1.1" 404 Not Found
```

**Comment by AbdullahAlfaraj** [comment]
@jackhagley check my answer in this issue https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/43#issuecomment-1369720783 , it might help.
