### ISSUE TITLE
Struggling to get anything working

### ISSUE THREAD

**Issue by Gibraltor** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#319]
Originally my buddy showed me the photoshop app, so I downloaded it straight, couldn't get it to work. Dug deeper, learned I need python and git, got those, made my stable-fusion folder, and that's as far as I can go, I edited the webui-user.bat like I was told to do and I added the pruned 1.5 model. But that's it, all I get is errors now, I can't get the IP address at all to work. Please help, I have the code here.

"You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

venv "C:\Users\Joel Davis\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 076d624a297532d6e4abebe5807fd7c7504d7a73
Fetching updates for Taming Transformers...
Checking out commit for Taming Transformers with hash: 24268930bf1dce879235a7fddd0b2355b84d7ea6...
Traceback (most recent call last):
  File "C:\Users\Joel Davis\stable-diffusion-webui\launch.py", line 360, in <module>
    prepare_environment()
  File "C:\Users\Joel Davis\stable-diffusion-webui\launch.py", line 301, in prepare_environment
    git_clone(taming_transformers_repo, repo_dir('taming-transformers'), "Taming Transformers", taming_transformers_commit_hash)
  File "C:\Users\Joel Davis\stable-diffusion-webui\launch.py", line 156, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "C:\Users\Joel Davis\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 24268930bf1dce879235a7fddd0b2355b84d7ea6 for Taming Transformers.
Command: "git" -C "repositories\taming-transformers" checkout 24268930bf1dce879235a7fddd0b2355b84d7ea6
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: 24268930bf1dce879235a7fddd0b2355b84d7ea6"

**Comment by TRGLN** [comment]
For a fully automatic installation of Stable Diffusion, you can use the Super Easy Installer Tool
https://github.com/diStyApps/seait/releases/tag/0.1.4
You need to install Automatic1111webui
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/c58ece8d-07e8-47f0-b7ad-345e289be2af)
Then you need to download the weights of the model (this is a file with the extension **.safetensors** or **.ckpt**)
They can be downloaded from civitai.com
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/f0bb2280-6066-4eca-9708-f0a2ec922e8f)
or from huggingface.co (direct link below)
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors
then the downloaded model should be placed in the folder where automatic1111webui is installed
**...\stable-diffusion-webui\models\Stable-diffusion**
Now you can run Stable Diffusion, for this, in the Super Easy Installer Tool on the Automatic1111webui tab, click Launch
A browser will automatically open with the address **http://127.0.0.1:7860/** _(if not, enter the address in the browser manually)_
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/64064d1c-5ef5-468c-b976-4800a72ce502)

In order for the plugin for Photoshop to work, you need to follow all the steps above.
You need a minimum version of Photoshop v24
Next, follow the installation instructions on the main page of the plugin:
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin
p.s. The --api key required for operation can be added before starting Stable Diffusion in Seait, do not forget to click Save
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/d19a048f-39db-4a2e-ad35-edb71f2d0ad7)

This instruction will work for nvidia video cards, if you have AMD, additional steps are required to get the SD to work

**Comment by Gibraltor** [comment]
So I have NVIDIA, all I want is the photoshop stuff, do I have to do the other stuff first?

**Comment by Gibraltor** [comment]
And thanks for the swift reply!

**Comment by Gibraltor** [comment]
So after the first part of installing I get this. I'm unsure if it's an issue or not yet.

"Path cannot contain spaces. C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui
installing stable-diffusion-webui with at C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui
Cloning into 'C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui'...
remote: Enumerating objects: 22417, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 22417 (delta 5), reused 4 (delta 1), pack-reused 22405
Receiving objects: 100% (22417/22417), 30.42 MiB | 148.00 KiB/s, done.
Resolving deltas: 100% (15633/15633), done.
stable-diffusion-webui cloned into C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui
Creating virtual environment for stable-diffusion-webui at C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui\venv
Virtual environment created for stable-diffusion-webui at C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui\venv
'C:\Users\Joel' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Joel Davis\Downloads\seait.v0.1.4\seait.v0.1.4\stable-diffusion-webui>"

**Comment by Gibraltor** [comment]
Turns out it didn't like my user name, I moved it to public, seems to be launching stuff now.

**Comment by TRGLN** [comment]
You can try adding an argument: **--lowvram**
