### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by hansolocambo** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#341]
"First time running the plugin [...] "

"edit start_server.bat"
but this file is deprected innit ?

"run "start_server.bat" inside "Auto-Photoshop-StableDiffusion-Plugin" directory"
hmm.... no. So how to do it now ? 

etc.

Could you please update the installation notes for new users ? Pretty confusing as it is. 
Thank you.

**Comment by cakes93** [comment]
still outdated, please respond

**Comment by AbdullahAlfaraj** [comment]
I recommend installing the plugin using either [method 1](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#method-1-one-click-installer) (.ccx), or [method 2](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#method-2-the-unzip-method) (.zip). It's easier and more optimized for production.
Method 3 is only there for developers.

**Comment by cakes93** [comment]
For method 3, instead of running start_server.bat, we just install the extension in A1111, correct? There's nothing else that needs to be done?

**Comment by AbdullahAlfaraj** [comment]
>For method 3, instead of running start_server.bat, we just install the extension in A1111, correct? There's nothing else that needs to be done?


If you follow the instruction here [method 3](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#first-time-running-the-plugin-local-automatic1111):
- For step 1) This is where you install the plugin in Automatic1111.
- Skip step 4) since it’s deprecated.
- For step 7) Find a way to install UXP. The easiest way is through Creative Cloud.

follow the rest of the steps as described in the documentation.

**Comment by cakes93** [comment]
Thank you for updating the instructions. Just wanted to confirm since I'm troubleshooting and deprecated often means there's a newer alternative.

**Comment by naql** [comment]
Ok, so I have an installation issue and do not want to open a new issue, so I will just append my questions here:

I have installed the Automatic1111 extension for Photoshop plugin and both it and Automatic are up to date. 
I have enabled Developer Mode in PhotoShop v 24.7
I have installed Adobe UXP Developer Tool.

I loaded the .json file in UXP Developer tool and the plugin loads successfully and appears in PhotoShop. BUT...
There are no generation buttions, I cannot access any of the other tabs, e.g., "Settings".

In the UXP Developer console, I see this error:
`Uncaught Error: Module not found: "./typescripts/dist/bundle". Parent module folder was: "/".
    at e.exports._throwModuleNotFound (uxp://uxp-internal/runtime_scripts_loader.js:2:18761)
    at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19733)
    at a (uxp://uxp-internal/runtime_scripts_loader.js:2:19003)
    at D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\sdapi_py_re.js:6:25
    at e.exports._loadModule (uxp://uxp-internal/runtime_scripts_loader.js:2:21184)
    at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19696)
    at a (uxp://uxp-internal/runtime_scripts_loader.js:2:19003)
    at D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\utility\tab\sd.js:6:15
    at e.exports._loadModule (uxp://uxp-internal/runtime_scripts_loader.js:2:21184)
    at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19696)`

I turned on api logging and I see no interactions with the server.  I also have it running on a non-standard port and was not sure if I needed to configure that, but I don't think I am getting that far.  (As I don't think it is fully loading and there is no settings tab.)

Please advise, and thank you for creating this.

**Comment by KINGLIFER** [comment]
> Thank you for updating the instructions. Just wanted to confirm since I'm troubleshooting and deprecated often means there's a newer alternative.

Did you get this to work? I have no idea why it is mixed with outdated information. Do you have a clean clear documentation I could follow? Thanks.
