### ISSUE TITLE
Module not found: "./typescripts/dist/bundle"

### ISSUE THREAD

**Issue by naql** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#352]
I have installed the Automatic1111 extension for Photoshop plugin and both it and Automatic are up to date.
I have enabled Developer Mode in PhotoShop v 24.7
I have installed Adobe UXP Developer Tool.

I loaded the .json file in UXP Developer tool and the plugin loads successfully and appears in PhotoShop. BUT...
There are no generation buttions, I cannot access any of the other tabs, e.g., "Settings".

In the UXP Developer console, I see this error:
Uncaught Error: Module not found: "./typescripts/dist/bundle". Parent module folder was: "/". at e.exports._throwModuleNotFound (uxp://uxp-internal/runtime_scripts_loader.js:2:18761) at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19733) at a (uxp://uxp-internal/runtime_scripts_loader.js:2:19003) at D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\sdapi_py_re.js:6:25 at e.exports._loadModule (uxp://uxp-internal/runtime_scripts_loader.js:2:21184) at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19696) at a (uxp://uxp-internal/runtime_scripts_loader.js:2:19003) at D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\utility\tab\sd.js:6:15 at e.exports._loadModule (uxp://uxp-internal/runtime_scripts_loader.js:2:21184) at e.exports._require (uxp://uxp-internal/runtime_scripts_loader.js:2:19696)

I turned on api logging and I see no interactions with the server. I also have it running on a non-standard port and was not sure if I needed to configure that, but I don't think I am getting that far. (As I don't think it is fully loading and there is no settings tab.)

Please advise, and thank you for creating this.

**Comment by zombieyang** [comment]
if you cloned or downloaded the code of this project to your disk, you have to run `npm install` and `npm run build` in the root of the code

**Comment by naql** [comment]
Well, I installed it via the extension page of Automatic1111.  Then, it sat unused for a while until I got around to it and realized I had to install it on the Photoshop side.

SO, I ran npm install and npm run build in the folder stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin
and got these errors on the build:

`PS D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin> npm install
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
added 789 packages from 471 contributors and audited 789 packages in 56.022s
found 24 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin> npm run build
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> uxp-template-default-starter@1.0.0 build D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin
> npx webpack --config webpack.config.js

openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
asset bundle.js 4.55 MiB [emitted] (name: bundle)
runtime modules 1.29 KiB 7 modules
cacheable modules 1.67 MiB
  modules by path ./node_modules/ 1.38 MiB 55 modules
  modules by path ./typescripts/ 297 KiB 46 modules
modules with errors 117 bytes [errors]
  ./icon/move_to_canvas.svg 39 bytes [not cacheable] [built] [code generated] [1 error]
  ./icon/pen.svg 39 bytes [not cacheable] [built] [code generated] [1 error]
  ./icon/preview.svg 39 bytes [not cacheable] [built] [code generated] [1 error]
external "uxp" 42 bytes [built] [code generated]
external "photoshop" 42 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]

ERROR in ./icon/move_to_canvas.svg
Module build failed (from ./node_modules/@svgr/webpack/dist/index.js):
D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\cosmiconfig\dist\index.js:79
  const overrideOptions = metaConfig.config ?? {};
                                             ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\@svgr\core\dist\index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
 @ ./typescripts/util/elements.tsx 17:27-67
 @ ./typescripts/ultimate_sd_upscaler/scripts.tsx 40:19-46
 @ ./typescripts/entry.ts 34:31-72

ERROR in ./icon/pen.svg
Module build failed (from ./node_modules/@svgr/webpack/dist/index.js):
D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\cosmiconfig\dist\index.js:79
  const overrideOptions = metaConfig.config ?? {};
                                             ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\@svgr\core\dist\index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
 @ ./typescripts/util/elements.tsx 19:16-45
 @ ./typescripts/ultimate_sd_upscaler/scripts.tsx 40:19-46
 @ ./typescripts/entry.ts 34:31-72

ERROR in ./icon/preview.svg
Module build failed (from ./node_modules/@svgr/webpack/dist/index.js):
D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\cosmiconfig\dist\index.js:79
  const overrideOptions = metaConfig.config ?? {};
                                             ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\node_modules\@svgr\core\dist\index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
 @ ./typescripts/util/elements.tsx 21:20-53
 @ ./typescripts/ultimate_sd_upscaler/scripts.tsx 40:19-46
 @ ./typescripts/entry.ts 34:31-72

webpack 5.82.1 compiled with 3 errors in 23622 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uxp-template-default-starter@1.0.0 build: `npx webpack --config webpack.config.js`
npm ERR! Exit status 1`

**Comment by AbdullahAlfaraj** [comment]
> const overrideOptions = metaConfig.config ?? {};
^
SyntaxError: Unexpected token '?'

It seems that you may be using an outdated version of Node.js that does not support the "??" nullish coalescing operator. If you do not intend to modify the source code, it would be much simpler to install the plugin using the compiled .ccx or .zip file available in the release section.
