### ISSUE TITLE
Having trouble with inpaint mode:TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by DponXiaodong** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#357]
SD 1.5.1
Plugin ver 1.3.0
log:
Total progress: 0it [00:00, ?it/s]preprocessor_list: []
model_list: []
sd_vae_dict: ['Automatic', 'None']
successful mask expansion operation
successful mask expansion operation
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/img2img {'error': 'TypeError', 'detail': '', 'body': '', 'errors': "'<' not supported between instances of 'int' and 'NoneType'"}
    Traceback (most recent call last):
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\stable-diffusion\sd.webui\webui\modules\api\api.py", line 152, in exception_handling
        return await call_next(request)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\stable-diffusion\sd.webui\webui\modules\api\api.py", line 116, in log_and_time
        res: Response = await call_next(req)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
        await self.app(scope, receive, send)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "D:\stable-diffusion\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "D:\stable-diffusion\sd.webui\webui\modules\api\api.py", line 365, in img2imgapi
        self.default_script_arg_img2img = self.init_default_script_args(script_runner)
      File "D:\stable-diffusion\sd.webui\webui\modules\api\api.py", line 264, in init_default_script_args
        if last_arg_index < script.args_to:
    TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by DponXiaodong** [comment]
I resolved the issue by reinstalling the plugin from the 'available' page in the web UI extension, contrary to what the tutorial suggested to install from the 'install from URL' page.
