### ISSUE TITLE
found conflicting dependencies while installing the automatic1111 plugin

### ISSUE THREAD

**Issue by zhongzishi** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#415]
```
ERROR: Cannot install -r ./extensions/Auto-Photoshop-StableDiffusion-Plugin/requirements.txt (line 22), click==8.1.3 and duckduckgo-search==3.9.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

The above error prevents webui from starting.

Removing version limit for duckduckgo-search allows webui to start but generates another error :

```
python_server_full_path:  /stable-diffusion-webui/extensions/Auto-Photoshop-StableDiffusion-Plugin/server/python_server
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/extensions/Auto-Photoshop-StableDiffusion-Plugin/server/python_server/search.py", line 4, in <module>
        from duckduckgo_search import AsyncDDGS
    ImportError: cannot import name 'AsyncDDGS' from 'duckduckgo_search' (/opt/conda/lib/python3.10/site-packages/duckduckgo_search/__init__.py)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/stable-diffusion-webui/extensions/Auto-Photoshop-StableDiffusion-Plugin/scripts/main.py", line 25, in <module>
        import search
      File "/stable-diffusion-webui/extensions/Auto-Photoshop-StableDiffusion-Plugin/server/python_server/search.py", line 6, in <module>
        raise ImportError(
    ImportError: duckduckgo_search is required to image search. Please install it with `pip install --upgrade duckduckgo_search`.
```

**Comment by zhongzishi** [comment]
finally found the problem, must make the plugin work to receive the correct inpaint result.
