### ISSUE TITLE
Runtime error - Comfyui backend

### ISSUE THREAD

**Issue by drprs** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#435]
Hi I am getting this error when using comfy backend
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

LOG:
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "J:\comfy 249\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "J:\comfy 249\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "J:\comfy 249\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "J:\comfy 249\ComfyUI\nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "J:\comfy 249\ComfyUI\comfy\sd.py", line 235, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples).to(self.output_device).float() + 1.0) / 2.0, min=0.0, max=1.0)
  File "J:\comfy 249\ComfyUI\comfy\taesd\taesd.py", line 71, in decode
    x_sample = self.taesd_decoder(x * self.vae_scale)
  File "J:\comfy 249\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "J:\comfy 249\python_embeded\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "J:\comfy 249\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "J:\comfy 249\python_embeded\lib\site-packages\torch\nn\modules\upsampling.py", line 156, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
  File "J:\comfy 249\python_embeded\lib\site-packages\torch\nn\functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

Works perfectly with Automatic1111

**Comment by AbdullahAlfaraj** [comment]
Hey, could you share the arguments you’re using with ComfyUI? Also, it’d be super helpful if you could send a screenshot of the plugin settings. This way, I can try to replicate your setup on my end.

**Comment by drprs** [comment]
Issue was with the vae. It got resolved once cleared the vae folder and put the default vae from huggingface
