### ISSUE TITLE
ComfyUI   FileNotFoundError

### ISSUE THREAD

**Issue by WoNova** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#437]
Traceback (most recent call last):
  File "D:\AI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI\\custom_nodes\\Auto-Photoshop-StableDiffusion-Plugin\\__init__.py'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Cannot import D:\AI\ComfyUI\custom_nodes\Auto-Photoshop-StableDiffusion-Plugin module for custom nodes: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI\\custom_nodes\\Auto-Photoshop-StableDiffusion-Plugin\\__init__.py'

**Comment by AbdullahAlfaraj** [comment]
You shouldn't place Auto-Photoshop-StableDiffusion-Plugin in custom_nodes
Auto-Photoshop-SD is photoshop plugin, you install it in photoshop
Comfy-Photoshop-SD is custom_nodes you install in ComfyUI to connect ComfyUI to the photoshop plugin (Auto-Photoshop-SD)
follow the instruction here to install Comfy-Photoshop-SD:  
https://github.com/AbdullahAlfaraj/Comfy-Photoshop-SD?tab=readme-ov-file#how-to-install
