### ISSUE TITLE
sd-forge-controlnet support?

### ISSUE THREAD

**Issue by ktee95** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#466]
Please support SD-Forge built-in ControlNET , it's a simple version of Controlnet work with Stable Diffusion Forge. 
https://github.com/lllyasviel/stable-diffusion-webui-forge/tree/main/extensions-builtin/sd_forge_controlnet

**Comment by Stone-dielianhua** [comment]
strongly agree

**Comment by ktee95** [comment]
where is dev man?

**Comment by GeminiSquishGames** [comment]
I also agree. It's kind of essential for me since it's the only way I can reliably use XL models in photoshop and have access to controlnet, otherwise I have to use Comfy and Krita.

**Comment by lilngu** [comment]
> I also agree. It's kind of essential for me since it's the only way I can reliably use XL models in photoshop and have access to controlnet, otherwise I have to use Comfy and Krita.

Forge version is best optimized ever

**Comment by v4806** [comment]
非常同意!

**Comment by bluelovers** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/684

**Comment by Absinthze** [comment]
This is a much needed feature for me as well.

**Comment by an303042** [comment]
+1

**Comment by yesitsno0ne** [comment]
+1

**Comment by Absinthze** [comment]
It looks as if the developer has been offline from Github since December 2023.  Is it possible someone could pick this up as a Fork and continue the work?

**Comment by GeminiSquishGames** [comment]
> It looks as if the developer has been offline from Github since December 2023. Is it possible someone could pick this up as a Fork and continue the work?

Pretty sure that's what #478 is attempting, up above a few posts. Edit: You can get the repo like normal and it shouldn't get over written unless the extension detects a need to update. But the only change doesn't seem to do anything to help the issue at this time. I thought that it would need a path to where the control net files were but that didn't do anything. I also tried the setting to let other scripts take control of controlnet but that didn't help either.

Also, this functionality we require probably needs the dev2 branch of Forge, not the main. https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/692 is the request to add better ControlNet support with API.

I had to change the line 6 of clip.py to "import packaging" to make it run of the dev2 repo version. It won't find pkg_resources as a module for whatever reason. Python dependencies and packaging is sometimes confusing when relying on other peoples code and pip to do things for you.

Edit: This seems to be an error with Stability Matrix, which I use to manage versions, that was fixed yesterday.

**Comment by zombieyang** [comment]
Hi, I'm one of the contributor of this repository before. And I started another project to provide a more lightweight tool to connect PS and SD/SD Forge/Comfy:

https://github.com/zombieyang/sd-ppp

**Comment by ktee95** [comment]
> Hi, I'm one of the contributor of this repository before. And I started another project to provide a more lightweight tool to connect PS and SD/SD Forge/Comfy:
> 
> https://github.com/zombieyang/sd-ppp

Your plugin is very promising. What I think users want most right now is a plugin that is fully compatible with the final version of SD webui (A1111, SD Next) and ControlNet, for both text2img and img2img. That's it! Good work bro!

**Comment by ktee95** [comment]
> > It looks as if the developer has been offline from Github since December 2023. Is it possible someone could pick this up as a Fork and continue the work?
> 
> Pretty sure that's what #478 is attempting, up above a few posts. However, the original extension is written to replace the code with Abdullah's original repo upon loading the extention. So it'll just overwrite if you manually add bluelovers changes, since no one is there to approve the merge, it won't be officially added unless whoever has access to Abdullah's repo can merge it.
> 
> Also, this functionality we require probably needs the dev2 branch of Forge, not the main. [lllyasviel/stable-diffusion-webui-forge#692](https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/692) is the request to add better ControlNet support with API.
> 
> I had to change the line 6 of clip.py to "import packaging" to make it run of the dev2 repo version. It won't find pkg_resources as a module for whatever reason. Python dependencies and packaging is sometimes confusing when relying on other peoples code and pip to do things for you.
> 
> Edit: This seems to be an error with Stability Matrix, which I use to manage versions, that was fixed yesterday.

As you stated, to make this plugin compatible with SD Forge, we have to manually modify the extension files locally? 
Let me know if you have done it successfully? Does it work? Looking forward to your respones.

**Comment by Absinthze** [comment]
I wish I could help guys, I'm just a user not a coder.   I wish you great success and thank you for your efforts!

**Comment by GeminiSquishGames** [comment]
> > > It looks as if the developer has been offline from Github since December 2023. Is it possible someone could pick this up as a Fork and continue the work?
> > 
> > 
> > Pretty sure that's what #478 is attempting, up above a few posts. However, the original extension is written to replace the code with Abdullah's original repo upon loading the extention. So it'll just overwrite if you manually add bluelovers changes, since no one is there to approve the merge, it won't be officially added unless whoever has access to Abdullah's repo can merge it.
> > Also, this functionality we require probably needs the dev2 branch of Forge, not the main. [lllyasviel/stable-diffusion-webui-forge#692](https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/692) is the request to add better ControlNet support with API.
> > I had to change the line 6 of clip.py to "import packaging" to make it run of the dev2 repo version. It won't find pkg_resources as a module for whatever reason. Python dependencies and packaging is sometimes confusing when relying on other peoples code and pip to do things for you.
> > Edit: This seems to be an error with Stability Matrix, which I use to manage versions, that was fixed yesterday.
> 
> As you stated, to make this plugin compatible with SD Forge, we have to manually modify the extension files locally? Let me know if you have done it successfully? Does it work? Looking forward to your respones.

I looked into what bluelovers change and it looks for a JSON file for the setting in one line. I'm not sure if that is all that is needed to make it work with dev2 branch of forge. I haven't had time to look into preventing the original extension from auto updating when web-ui starts, should just be in the initialization of the extension, but I'll try that after I look into @zombieyang 's contributions a bit. It might be good to have a more modern solution if we can't get the extension and .ccx plugin source needed to improve for future technology. I will let you know what I come up with.

**Comment by GeminiSquishGames** [comment]
> Hi, I'm one of the contributor of this repository before. And I started another project to provide a more lightweight tool to connect PS and SD/SD Forge/Comfy:
> 
> https://github.com/zombieyang/sd-ppp

When using it with Forge, I can't get any results. It finds the layers but doesn't do anything when I try getting or sending. I'm getting the following error when performing get:

`ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1669' coro=<AsyncServer._handle_event_internal() done, defined at D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\socketio\async_server.py:608> exception=Exception('sdppp PS side error:HTTP 422')>
Traceback (most recent call last):
  File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\socketio\async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\socketio\async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
  File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-ppp\sdppp_python\apis.py", line 80, in c_get_image
    upload_name, opacity = await photoshopInstance.get_image(layer_id=id, bounds_id=bounds_id)
  File "D:\Graphics\stability matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-ppp\sdppp_python\photoshop_instance.py", line 59, in get_image
    raise Exception('sdppp PS side error:' + result['error'])
Exception: sdppp PS side error:HTTP 422`

Send creates a new layer but doesn't actually push the image to it, it doesn't seem to make an error.

**Comment by lcretan** [comment]
Hi,

I agree that the interoperability between Forge is meaningful for both.

Forge might seem to be frozen, but it's awake and ready to adapt to any key important events in this domain.

The developer of Forge has an academic background in theoretical research of multimodal GenAI, as evidenced by his academic papers, so he is always keenly catching any important key movements and adapts Forge to such key triggers. 

For example, adapted by extremely optimized codes with SD3/3.5, flux1, and other game changers. Furthermore, Controlnet is one of his inventions, and Controlnet v1.1 has released.
The current ones are Layer Diffuse, which is a stacked transparent layer that only has the main center image and can easily manipulate them independently, and FramePack, a commodity game pc only 8GB VRAM can produce the video for some minutes.
