### ISSUE TITLE
After upgrading auto1111 SD from 1.7 to 1.9.3, plugin failing randomly

### ISSUE THREAD

**Issue by Jonseed** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#486]
This is a great plugin, I use it all the time. Thank you for your work on this. I just upgraded auto1111 SD from 1.7 to 1.9.3 (I also upgraded torch and xformers), and it works fine in the gradio interface. And I thought it was working fine with this plugin in Photoshop. I did some upscales, and it seemed to be working. But it just started failing when I try to run any generation in any mode. It says "Interrupt" for a split second, and then returns to the default buttons, and nothing happens. No popup error and nothing shows up in the console either. I've tried restarting Photoshop, without success. Any idea what might be causing it to fail, and how I can diagnose the problem? If I fiddle with it enough, sometimes I can eventually get it to work again, but I'm not sure if it is a particular setting that is the problem, or a bug somewhere. If I look in the log file, I do see this error. Not sure if it is related:

> "warning": "getUniqueDocumentId is deprecated, instead use the methods in IOFolder",
>     "stackTrace": "Error\n    at console.warn (index.js:128:31)\n    at getUniqueDocumentId (index.js:270:13)\n    at Object.getSettings (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\utility\\session.js:246:40)\n    at Function.getSettings (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\typescripts\\dist\\bundle.js:2:426933)\n    at Function.getSettings (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\typescripts\\dist\\bundle.js:2:441858)\n    at Function.generate (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\typescripts\\dist\\bundle.js:2:442744)\n    at async I (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\typescripts\\dist\\bundle.js:2:423033)\n    at async C (C:\\Users\\X\\AppData\\Roaming\\Adobe\\UXP\\Plugins\\External\\auto.photoshop.stable.diffusion.plugin_1.4.1\\typescripts\\dist\\bundle.js:2:424521)"

**Comment by cdmusic2019** [comment]
webui Try not to upgrade to the latest version, just upgrade to 1.8. The plugin has a bit of a problem supporting version 1.9, such as the sampler.

**Comment by Jonseed** [comment]
Will the plugin be updated to support version 1.9? There haven't been any commits for 5 months. Is the plugin abandoned?

**Comment by ktee95** [comment]
Looks like the devs abandoned it

**Comment by dougbtv** [comment]
See also #488 -- what I'm encountering is similar. I tuned on api logging in auto1111 and I'm seeing 422 responses from the api server

**Comment by dougbtv** [comment]
any luck with 1.8 by the way?

**Comment by Jonseed** [comment]
> any luck with 1.8 by the way?

Yes, 1.8 seems to work just fine.
