### ISSUE TITLE
 raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AstorScriabin** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#49]
The plugin has been loaded successfully and AUTOMATIC1111 works correctly. But getting JSONDecodeError when clicking "generate" inside photoshop

![image](https://user-images.githubusercontent.com/47272540/211209846-9be45773-418d-4b38-9ff1-c83f0e2bf25f.png)

`txt2ImgHandle:

payload:  {'prompt': 'cute cat, {painterly_style_1}', 'negative_prompt': '{ugly}', 'steps': '20', 'sampler_index': 'Euler a', 'width': 512, 'height': 512, 'enable_hr': False, 'firstphase_width': 512, 'firstphase_height': 512, 'denoising_strength': 0.7000000000000001, 'batch_size': '1', 'cfg_scale': 7, 'seed': '-1', 'mask_blur': 7, 'use_prompt_shortcut': False, 'prompt_shortcut_ui_dict': {}, 'uniqueDocumentId': '0e8459b0-0a66-4bad-b245-e9f7e992beab', 'mode': 'txt2img'}
[32mINFO[0m:     127.0.0.1:51171 - "[1mPOST /txt2img/ HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server\python_server\.\serverMain.py", line 157, in txt2ImgHandle
    dir_name,image_paths,metadata = await txt2ImgRequest(payload)
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server\python_server\.\serverMain.py", line 38, in txt2ImgRequest
    r = response.json()
  File "C:\Users\Administrator\Downloads\Auto-Photoshop-StableDiffusion-Plugin-master\Auto-Photoshop-StableDiffusion-Plugin-master\server_env\lib\site-packages\httpx\_models.py", line 752, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[32mINFO[0m:     127.0.0.1:51174 - "[1mGET /sdapi/v1/progress?skip_current_image=false HTTP/1.1[0m" [32m200 OK[0m`

**Comment by AbdullahAlfaraj** [comment]
``` Exception in ASGI application``` 
this error is usually caused by an outdated auto1111 version. Therefore, update it your webui to the latest version should resolve it.
