### ISSUE TITLE
Extras Upscaling not working. Error in Console.

### ISSUE THREAD

**Issue by Wowmandeez** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#491]
Outpainting working great, looks amazing however inevitably low res due to the 512 resolution. I decide to try to upscale it using the extras tab. but am presented with an error. the inability to upscale makes the tool essentially useless for outpainting due to the resolution. Im sure its a problem on my end but I cant figure it out.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/108247865/cd884ef7-dbdc-41e8-85aa-59e0783e567c)
These are my settings, though the issue persists with all upscaler models.

Heres my console log.

```
tiled upscale: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.41it/s]
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/extra-single-image {'error': 'TypeError', 'detail': '', 'body': '', 'errors': "'NoneType' object is not callable"}
    Traceback (most recent call last):
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\Stable\stable-diffusion-webui\modules\api\api.py", line 186, in exception_handling
        return await call_next(request)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "F:\Stable\stable-diffusion-webui\modules\api\api.py", line 150, in log_and_time
        res: Response = await call_next(req)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
        await self.app(scope, receive, send)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "E:\Projects\AI_art\Automatic1111\stable-diffusion-webui\venv\pyenv.cfg\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "F:\Stable\stable-diffusion-webui\modules\api\api.py", line 565, in extras_single_image_api
        result = postprocessing.run_extras(extras_mode=0, image_folder="", input_dir="", output_dir="", save_output=False, **reqDict)
      File "F:\Stable\stable-diffusion-webui\modules\postprocessing.py", line 161, in run_extras
        return run_postprocessing(extras_mode, image, image_folder, input_dir, output_dir, show_extras_results, *args, save_output=save_output)
      File "F:\Stable\stable-diffusion-webui\modules\postprocessing.py", line 71, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "F:\Stable\stable-diffusion-webui\modules\scripts_postprocessing.py", line 198, in run
        script.process(single_image, **process_args)
      File "F:\Stable\stable-diffusion-webui\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 238, in process
        detected_map = module(
    TypeError: 'NoneType' object is not callable

---



```

**Comment by Wowmandeez** [comment]
Okay well that was quick but I solved it by disabling the "CN In Extras Tab" Extension. Appears to cause a conflict. Hope this helps eithers the Devs or anyone else having the issue
