### ISSUE TITLE
vae error, not vae list,unable generate,comfy ui

### ISSUE THREAD

**Issue by YmStrip** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#495]
Prompt executed in 1.98 seconds
got prompt
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00,  7.91it/s]
!!! Exception during processing!!! 'VAE' object has no attribute 'vae_dtype'
Traceback (most recent call last):
  File "D:\ai\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 268, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\sd.py", line 293, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
                                                            ^^^^^^^^^^^^^^
AttributeError: 'VAE' object has no attribute 'vae_dtype'

Prompt executed in 2.02 seconds
everything works fine in webui and comfyui(direct generation)

but when you start ps for the first time, it accidentally refreshes the list of available vae, and when you click refresh again it disappears, and the error occurs regardless of whether or not a vae is selected.

ComfyUI Revision: 2216 [91542d4f] | Released on '2024-05-28'

some times 

for input of size 409600
.....
ERROR lora diffusion_model.output_blocks.5.1.proj_out.weight shape '[1280, 1280, 1, 1]' is invalid for input of size 409600
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.90it/s]
WARNING: No VAE weights detected, VAE not initalized.
.....
* KSampler 3:
  - Failed to convert an input value to a INT value: steps, None, int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Output will be ignored
....
After that, it's all like this.
!!! Exception during processing!!! 'VAE' object has no attribute 'vae_dtype'

happen:  txt2img(yes) img2img(yes) inpaint(yes) outpaint(yes)

Thanks

**Comment by morgan55555** [comment]
Same thing, VAE list is loaded once after starting Photoshop, and cannot be updated or selected (If I choose one of VAE, this is not changing at all.)
Currently the only fix is renaming VAE, 'cause this addon will load first VAE in alphabetical order, or using custom workflow.
Hope that it will be fixed soon for my ComfyUI build.
