### ISSUE TITLE
Img2Img is broken

### ISSUE THREAD

**Issue by NeilFranks** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#496]
Using auto1111 backend. Img2Img works in auto1111.

On fresh install of both auto1111 and this plugin.

payload's `init_images` is `[None]`.

Full stacktrace:

```
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/img2img {'error': 'AttributeError', 'detail': '', 'body': '', 'errors': "'NoneType' object has no attribute 'startswith'"}
    Traceback (most recent call last):
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Neilm\webui\modules\api\api.py", line 196, in exception_handling
        return await call_next(request)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "C:\Users\Neilm\webui\modules\api\api.py", line 158, in log_and_time
        res: Response = await call_next(req)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
        await self.app(scope, receive, send)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "C:\Users\Neilm\webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "C:\Users\Neilm\webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "C:\Users\Neilm\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "C:\Users\Neilm\webui\modules\api\api.py", line 611, in img2imgapi
        p.init_images = [decode_base64_to_image(
      File "C:\Users\Neilm\webui\modules\api\api.py", line 611, in <listcomp>
        p.init_images = [decode_base64_to_image(
      File "C:\Users\Neilm\webui\modules\api\api.py", line 80, in decode_base64_to_image
        if encoding.startswith("http://") or encoding.startswith("https://"):
    AttributeError: 'NoneType' object has no attribute 'startswith'
```
    
It might be related to this empty area for "Image" in the plugin? I can't click on it or get any init image in there, if that's what I'm supposed to do? It used to just work with a rectangular selection on the canvas.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/29698185/03ee407a-3501-4985-8015-d679e44f0597)

**Comment by GeminiSquishGames** [comment]
The python error is just because there is no image data for it to use, which you probably figured out, but Img2Img needs something to use for vae to encode and put in the latent space. init_images = none means there aren't any images there to img2img with. The plugin should use whatever is selected even a transparent layer. It may be erroring out if you have a bad VAE selected or is being Auto selected in the Settings. Try setting VAE to none in the last tab of the plugin. Restart otherwise, if restarting Photoshop doesn't fix it you may need to try re-installing the .ccx file. If that doesn't fix it would need to know what version photoshop is and what may have changed on your system since the last time it was working, and if all models/checkpoints do this and without VAE, LoRA, or Embeddings as well as maybe turning off all extensions other than the Photoshop one to help debug. Unfortunately, we aren't likely to see any fixes to problems with this repo as the dev hasn't been active in several months, so hopefully it's not that.
